# Generated by Django 4.2.2 on 2023-06-06 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='notification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat_app.notification'),
        ),
        migrations.AlterField(
            model_name='user',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat_app.request'),
        ),
    ]
